"""Joined DB into Review Class

Revision ID: 0a4f97d18906
Revises: cb0278aeb10a
Create Date: 2020-08-13 10:12:11.788600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a4f97d18906'
down_revision = 'cb0278aeb10a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_all_groups_group_name', table_name='all_groups')
    op.drop_index('ix_all_groups_group_type', table_name='all_groups')
    op.drop_table('all_groups')
    op.drop_table('keywords')
    op.drop_table('problem_space')
    op.drop_table('manage_group')
    op.drop_table('solution_space')
    op.add_column('reviews', sa.Column('group_name', sa.String(length=64), nullable=True))
    op.add_column('reviews', sa.Column('group_type', sa.String(length=16), nullable=True))
    op.add_column('reviews', sa.Column('keyword_list', sa.Text(), nullable=True))
    op.add_column('reviews', sa.Column('problem_space_text', sa.Text(), nullable=True))
    op.add_column('reviews', sa.Column('solution_space_text', sa.Text(), nullable=True))
    op.add_column('reviews', sa.Column('tt_groups', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_reviews_group_name'), 'reviews', ['group_name'], unique=False)
    op.create_index(op.f('ix_reviews_group_type'), 'reviews', ['group_type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_group_type'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_group_name'), table_name='reviews')
    op.drop_column('reviews', 'tt_groups')
    op.drop_column('reviews', 'solution_space_text')
    op.drop_column('reviews', 'problem_space_text')
    op.drop_column('reviews', 'keyword_list')
    op.drop_column('reviews', 'group_type')
    op.drop_column('reviews', 'group_name')
    op.create_table('solution_space',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('solution_space_text', sa.TEXT(), nullable=True),
    sa.Column('review_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manage_group',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tt_groups', sa.INTEGER(), nullable=True),
    sa.Column('review_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('problem_space',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('problem_space_text', sa.TEXT(), nullable=True),
    sa.Column('review_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keywords',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('keyword_list', sa.TEXT(), nullable=True),
    sa.Column('group_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['all_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('all_groups',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('group_name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('group_type', sa.VARCHAR(length=16), nullable=True),
    sa.Column('manage_group_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['manage_group_id'], ['manage_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_all_groups_group_type', 'all_groups', ['group_type'], unique=False)
    op.create_index('ix_all_groups_group_name', 'all_groups', ['group_name'], unique=False)
    # ### end Alembic commands ###
